AC_INIT([libibsimu-1.0.4dev], [1.0.4dev], [taneli.kalvas@jyu.fi])
AM_CONFIG_HEADER(src/config.h)
AC_CONFIG_MACRO_DIR([m4])
AM_INIT_AUTOMAKE

AC_USE_SYSTEM_EXTENSIONS

AC_DEFUN(
	AC_GCC_SUPPORTS_RDYNAMIC,
	[
		AC_PATH_PROG([grep], [grep])
                echo -n "checking if the compiler supports -rdynamic... "
                if test "X${ac_compiler_gnu}X" = "XyesX"; then
                        if test "X`${CC} -dumpspecs | ${grep} rdynamic`X" != "XX"; then
                                echo "yes"
                                AC_SUBST([rdynamic_flag], ["-rdynamic"])
                        else
                                echo "no"
                                AC_SUBST([rdynamic_flag], [])
                        fi
                else
                        echo "no"
                        AC_SUBST([rdynamic_flag], [])
                fi
        ]
)
AC_GCC_SUPPORTS_RDYNAMIC([rdynamic_flag])


dnl ---------------------------------
dnl Check for programs
dnl ---------------------------------

m4_pattern_allow([AC_PROG_LIBTOOL])
AC_PROG_LIBTOOL
AC_PROG_CXX
dnl AC_PROG_RANLIB

dnl ---------------------------------
dnl pkgconfig
dnl ---------------------------------

PKG_PROG_PKG_CONFIG()
if test "x$PKG_CONFIG" = x; then
   AC_MSG_ERROR([pkg-config >= $PKGCONFIG_REQUIRED required but not
found (http://pkgconfig.freedesktop.org/)])
fi

dnl ---------------------------------
dnl Check for selectable compilation
dnl ---------------------------------

AC_ARG_WITH([umfpack],
  [AS_HELP_STRING([--with-umfpack],
                  [enable optional support for umfpack solver])],
                  [],
                  [with_umfpack=no])
AM_CONDITIONAL([UMFPACK], [test x$with_umfpack != xno])
if test x$with_umfpack != xno ; then
  PKG_CHECK_MODULES(umfpack, umfpack)
  CPPFLAGS="$CPPFLAGS $umfpack_CFLAGS"
  LIBS="$LIBS $umfpack_LIBS"
  AC_SUBST(UMFPACK_COND,umfpack)
else
  AC_SUBST(UMFPACK_COND,"")
fi


AC_ARG_WITH([csg],
  [AS_HELP_STRING([--with-csg],
                  [enable optional support for csg solids])],
                  [],
                  [with_csg=no])
AM_CONDITIONAL([CSG], [test x$with_csg != xno])
if test x$with_csg != xno ; then
  PKG_CHECK_MODULES(csg, csg)
  CPPFLAGS="$CPPFLAGS $csg_CFLAGS"
  LIBS="$LIBS $csg_LIBS"
  AC_SUBST(CSG_COND,csg)
else
  AC_SUBST(CSG_COND,"")
fi


dnl ---------------------------------
dnl Check for libraries
dnl ---------------------------------

dnl -------------
dnl libm

AC_CHECK_LIBM
CPPFLAGS="$CFLAGS $CPPFLAGS"
LIBS="$LIBS $LIBM"

dnl -------------
dnl zlib

CHECK_ZLIB()

dnl -------------
dnl gtk+-2.0

if $PKG_CONFIG --exists gtk+-2.0 ; then
  PKG_CHECK_MODULES(gtk, gtk+-2.0 >= 0.0.1 )
else
  AC_MSG_ERROR([required library gtk+-2.0 not found])
fi
LIBS="$LIBS $gtk_LIBS"
CPPFLAGS="$CPPFLAGS $gtk_CFLAGS"


dnl -------------
dnl libpng

if $PKG_CONFIG --exists libpng ; then
  PKG_CHECK_MODULES(libpng, libpng)
else
  AC_MSG_ERROR([required library libpng not found])
fi
LIBS="$LIBS $libpng_LIBS"
CPPFLAGS="$CPPFLAGS $libpng_CFLAGS"


dnl -------------
dnl fontconfig

if $PKG_CONFIG --exists fontconfig ; then
  PKG_CHECK_MODULES(fontconfig, fontconfig)
else
  AC_MSG_ERROR([required library fontconfig not found])
fi
LIBS="$LIBS $fontconfig_LIBS"
CPPFLAGS="$CPPFLAGS $fontconfig_CFLAGS"


dnl -------------
dnl Freetype2

if $PKG_CONFIG --exists freetype2 ; then
  PKG_CHECK_MODULES(freetype, freetype2)
else
  AC_MSG_ERROR([required library freetype2 not found])
fi
LIBS="$LIBS $freetype_LIBS"
CPPFLAGS="$CPPFLAGS $freetype_CFLAGS"


dnl -------------
dnl Cairo
dnl
dnl No accurate information about required cairo version. 
dnl Tested to work down to 1.2.4.

if $PKG_CONFIG --exists cairo ; then
  PKG_CHECK_MODULES(cairo, cairo >= 1.2.4 )
else
  AC_MSG_ERROR([required library cairo not found])
fi
LIBS="$LIBS $cairo_LIBS"
CPPFLAGS="$CPPFLAGS $cairo_CFLAGS"

dnl -------------
dnl csg
dnl 
dnl if $PKG_CONFIG --exists csg ; then
dnl   PKG_CHECK_MODULES(csg, csg >= 0.0.1 )
dnl else
dnl   AC_MSG_ERROR([required library csg not found])
dnl fi
dnl LIBS="$LIBS $csg_LIBS"
dnl CPPFLAGS="$CPPFLAGS $csg_CFLAGS"

dnl -------------
dnl POSIX threads 

ACX_PTHREAD()
LIBS="$LIBS $PTHREAD_LIBS $PTHREAD_CFLAGS"
CPPFLAGS="$CPPFLAGS $PTHREAD_CFLAGS"

dnl AC_CHECK_HEADERS([pthread.h])
dnl if $HAVE_PTHREAD_H ; then
dnl   LIBS="$LIBS -lpthread"
dnl else
dnl   AC_MSG_ERROR([required library pthread not found])
dnl fi

dnl -------------
dnl GSL

if $PKG_CONFIG --exists gsl ; then
  PKG_CHECK_MODULES(gsl, gsl >= 1.12 )
else
  AC_MSG_ERROR([required version of gsl not found])
fi
LIBS="$LIBS $gsl_LIBS"
CPPFLAGS="$CPPFLAGS $gsl_CFLAGS"

dnl AC_CHECK_LIB([gslcblas],[cblas_dgemm])
dnl AC_CHECK_LIB([gsl],[gsl_blas_dgemm])

dnl -------------
dnl Time

AC_CHECK_HEADERS([sys/time.h])
AC_HEADER_TIME
AC_CHECK_FUNCS([gettimeofday])

dnl ---------------------------------
dnl Output
dnl ---------------------------------

AC_CONFIG_FILES([Makefile src/Makefile tests/Makefile doc/Makefile doc/Doxyfile doc/Doxyfile_web ibsimu-1.0.4dev.pc])
AC_OUTPUT

	
